repos:
  - repo: local
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      types: [python]
    - id: flake8
      name: flake8
      entry: flake8
      language: python
      types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-docstring-first
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--no-sort-keys]
